!theme plain

skinparam {
	' フォント
	defaultFontName "Zen Kurenaido"
	defaultMonospacedFontName "Zen Kurenaido"
	DefaultFontSize 16

	' 手書きっぽく
	handwritten true

	' スペース
	Padding 8
	ParticipantPadding 10
	BoxPadding 8

	' 背景透過
	backgroundcolor transparent

	' フローチャートにおける条件判定のスタイル
	conditionStyle diamond

	' ノートは左寄せ
	NoteTextAlignment left
}

'vim:set noexpandtab:
